server:
  port: 8081
  servlet:
    context-path: /java-ms-crud

spring:
    application:
      name: java-ms-crud
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    jmx:
      enabled: false
    datasource:
      url:  jdbc:mysql://localhost:3306/crud?useTimezone=true&serverTimezone=America/Sao_Paulo
      username: tiago
      password: Tchampion1$

